#!/usr/bin/env bash

root_dir="$(git rev-parse --show-toplevel)"

dirname=$(basename "$root_dir")

mkdir -p "$HOME/memory/$dirname"

imagesnap -q -w 2 "$HOME/memory/$dirname/$(date +%s)_$(git rev-parse HEAD).jpg"

