#!/usr/bin/env bash

root_dir="$(git rev-parse --show-toplevel)"

dirname=$(basename "$root_dir")
message=$(head -1 "$root_dir/.git/COMMIT_EDITMSG")

mkdir -p "$HOME/memory/$dirname"

imagesnap -q -w 0.5 /tmp/test.jpg
convert /tmp/test.jpg -gravity North -pointsize 30 -annotate +0+100 "$message" "$HOME/memory/$dirname/$(date +%s)_$(git rev-parse HEAD).jpg"

